### PR TITLE
Scala 2.13

### PR DESCRIPTION
**Pull request by bneijt**
This is still work in progress as the scoverage plugin does not support 2.13 yet.

If you have any tips on getting SBT to stop loading the scoverage plugin for 2.13 I would be gratefull to put those changes in and update this PR.

### CODE REVIEW

**Comment by toddkazakov** [comment]
You can take a look at cats' build.sbt to see how to disable scoverage for 2.13 - https://github.com/typelevel/cats/blob/master/build.sbt

**Comment by bneijt** [comment]
The builds on Travis are flacky: sometimes they fail, sometimes they succeed.
Seems like there might be a broken nexus proxy on Travis or something else is randomly breaking the build. Retrying the jobs gets them to succeed.

Do you have any idea on fixing that as well? Could you trigger a restart of the jobs that failed for this MR?

**Comment by toddkazakov** [comment]
Are you sure all artifacts exist for 2.11? Don't really know how to fix it if they do and the issue is intermittent. I don't see a way to kick-off a new build either - for some reason I can't even sign in to Travis. I'll take a look in the next few days.

**Comment by bneijt** [comment]
https://circleci.com/gh/bneijt/prometheus-akka-http/4 Circle-CI build works at least, so you could also consider switching to Circle CI instead.

**Comment by oker1** [comment]
Can you resurrect this PR? At least a 2.12 build would be nice to have.

**Comment by toddkazakov** [comment]
There's already a 2.12 build that you can find here https://bintray.com/lonelyplanet/maven/prometheus-akka-http

```
<dependency>
  <groupId>com.lonelyplanet</groupId>
  <artifactId>prometheus-akka-http_2.12</artifactId>
  <version>0.4.0</version>
  <type>pom</type>
</dependency>
```

Feel free to submit a working PR for 2.13

**Comment by oker1** [comment]
Sorry I've missed the bintray repo part, _2.11 is available in jcenter, _2.12 needs your bintray repo.

The pr builds fine for me with `sbt clean +coverage +test +coverageReport`

**Comment by toddkazakov** [comment]
Builds seem to be ok now, but I don't quite understand why code coverage has decreased. I suspect it doesn't work under 2.13. I'll try to look into it the next couple of days.

**Comment by el-dom** [comment]
@toddkazakov Maybe i'm missing something, but looking at https://codecov.io/gh/lonelyplanet/prometheus-akka-http, i see it's only reporting 37.10% coverage for the `master` branch as well. 
So for me it doesn't make sense that the Codecov Report claims the coverage dropped from 43% to 37%. It was only 37% to begin with. 
The code lines mentioned in the coverage changes weren't covered before, so i wonder if this is just a bug in the report.

**Comment by toddkazakov** [comment]
Agreed - there's something funky going on. Unfortunately, I was quite busy. I'll try to take a look into this PR this weekend.

**Comment by kciesielski** [comment]
Hello, any updates on this?

**Comment by toddkazakov** [comment]
Released `0.5.0` with Akka 2.6.0 and support for Scala 2.12 and 2.13.

**Pull request closed without merging**
